services:
  backend:
    image: scouting:latest
    restart: unless-stopped
    container_name: sentinel
    profiles: [prod] # already exists
    ports:
      - "5000:5000"
    volumes:
      - appdata:/app # save all of the files to the volume

  backend-buildsource:
    build:
      context: .
      dockerfile: dockerimage/dockerfile
    image: scouting:latest
    restart: unless-stopped
    container_name: sentinel
    profiles: [localbuild] # build it yourself
    ports:
      - "5000:5000"
    volumes:
      - appdata:/app # save all of the files to the volume

  grafana:
    image: grafana-scouting:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana" # save all of the files
      - appdata:/app # share storage with flask
      - "./grafana-dashboard/grafana.ini:/etc/grafana/grafana.ini" # inject our grafana.ini into the grafana image
    profiles: [prod]
    extra_hosts:
      - "host.docker.internal:172.17.0.1" # ip may need to be changed, probably not

  grafana-buildsource:
    build:
      context: .
      dockerfile: grafana-dashboard/dockerfile
    image: grafana-scouting:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana" # save all of the files
      - appdata:/app # share storage with flask
      - "./grafana-dashboard/grafana.ini:/etc/grafana/grafana.ini" # inject our grafana.ini into the grafana image
    profiles: [localbuild]
    extra_hosts:
      - "host.docker.internal:172.17.0.1" # ip may need to be changed, probably not

volumes:
  appdata:
    driver: local
  grafana_storage: {}
