FROM python:slim

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY src src
COPY scouting_app.py key.txt ./
COPY dockerimage/boot.sh /
RUN chmod a+x /boot.sh

EXPOSE 5000
ENTRYPOINT [ "/boot.sh" ]