FROM python:slim

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY src src
COPY dockerimage/boot.sh scouting_app.py key.txt ./
RUN chmod a+x boot.sh

EXPOSE 5000
ENTRYPOINT [ "./boot.sh" ]