{
 "title": "Statbotics Viz",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Current_Match", "query": "SELECT Match\nFROM matches" }
  ]
 },
 "panels": [
  {
   "title": "Red Alliance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT Team, EPA\nFROM teams\nWHERE Team IN (\n  SELECT Red_1\n  FROM matches\n  WHERE Match = '2026paca_qm9'\n  UNION\n  SELECT Red_2\n  FROM matches\n  WHERE Match = '2026paca_qm9'\n  UNION\n  SELECT Red_3\n  FROM matches\n  WHERE Match = '2026paca_qm9'\n)",
     "rawQueryText": "SELECT Team, EPA\nFROM teams\nWHERE Team IN (\n  SELECT Red_1\n  FROM matches\n  WHERE Match = '$Current_Match'\n  UNION\n  SELECT Red_2\n  FROM matches\n  WHERE Match = '$Current_Match'\n  UNION\n  SELECT Red_3\n  FROM matches\n  WHERE Match = '$Current_Match'\n)"
    }
   ]
  },
  {
   "title": "Blue Alliance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT Team, EPA\nFROM teams\nWHERE Team IN (\n  SELECT Blue_1\n  FROM matches\n  WHERE Match = '2026paca_qm9'\n  UNION\n  SELECT Blue_2\n  FROM matches\n  WHERE Match = '2026paca_qm9'\n  UNION\n  SELECT Blue_3\n  FROM matches\n  WHERE Match = '2026paca_qm9'\n)",
     "rawQueryText": "SELECT Team, EPA\nFROM teams\nWHERE Team IN (\n  SELECT Blue_1\n  FROM matches\n  WHERE Match = '$Current_Match'\n  UNION\n  SELECT Blue_2\n  FROM matches\n  WHERE Match = '$Current_Match'\n  UNION\n  SELECT Blue_3\n  FROM matches\n  WHERE Match = '$Current_Match'\n)"
    }
   ]
  },
  {
   "title": "Red Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT Statbotics_red_score\nFROM matches\nWHERE Match = '2026paca_f1m1'",
     "rawQueryText": "SELECT Statbotics_red_score\nFROM matches\nWHERE Match = '$Current_Match'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Win Probability",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT Statbotics_red_win_prob\nFROM matches\nWHERE Match = '$Current_Match'",
     "rawQueryText": "SELECT Statbotics_red_win_prob\nFROM matches\nWHERE Match = '$Current_Match'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Blue Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT Statbotics_blue_score\nFROM matches\nWHERE Match = '2026paca_f1m1'",
     "rawQueryText": "SELECT Statbotics_blue_score\nFROM matches\nWHERE Match = '$Current_Match'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Expected RPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  (Statbotics_red_energized_rp + Statbotics_red_supercharged_rp + Statbotics_red_traversal_rp + (CASE WHEN Statbotics_winner = 'red' THEN 3 ELSE 0 END)) AS Expected_Rps\nFROM matches\nWHERE Match = '2026paca_f1m1'",
     "rawQueryText": "SELECT\n  (Statbotics_red_energized_rp + Statbotics_red_supercharged_rp + Statbotics_red_traversal_rp + (CASE WHEN Statbotics_winner = 'red' THEN 3 ELSE 0 END)) AS Expected_Rps\nFROM matches\nWHERE Match = '$Current_Match'"
    }
   ]
  },
  {
   "title": "Expected RPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  (Statbotics_blue_energized_rp + Statbotics_blue_supercharged_rp + Statbotics_blue_traversal_rp + (CASE WHEN Statbotics_winner = 'blue' THEN 3 ELSE 0 END)) AS Expected_Rps\nFROM matches\nWHERE Match = '$Current_Match'",
     "rawQueryText": "SELECT\n  (Statbotics_blue_energized_rp + Statbotics_blue_supercharged_rp + Statbotics_blue_traversal_rp + (CASE WHEN Statbotics_winner = 'blue' THEN 3 ELSE 0 END)) AS Expected_Rps\nFROM matches\nWHERE Match = '$Current_Match'"
    }
   ]
  }
 ]
}