[loggers]
keys=root,gunicorn.error,gunicorn.access,src,lib

[handlers]
keys=error_file,access_file,app_file

[formatters]
keys=simple

[logger_root]
level=INFO
handlers=error_file

[logger_gunicorn.error]
level=INFO
handlers=error_file
propagate=0
qualname=gunicorn.error

[handler_error_file]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=simple
kwargs={"filename": '/app/log/gunicorn/error.log', "mode": "a", "maxBytes": 10000000, "backupCount": 2}

[logger_gunicorn.access]
level=INFO
handlers=access_file
propagate=0
qualname=gunicorn.access

[handler_access_file]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=simple
kwargs={"filename": '/app/log/gunicorn/access.log', "mode": "a", "maxBytes": 10000000, "backupCount": 2}

[logger_src]
level=INFO
handlers=app_file
propagate=0
qualname=src

[logger_lib]
level=INFO
handlers=app_file
propagate=1
qualname=lib

[handler_app_file]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=simple
kwargs={"filename": '/app/log/gunicorn/app.log', "mode": "a", "maxBytes": 10000000, "backupCount": 2}

[formatter_simple]
format=%(asctime)s [%(levelname)s] %(name)s: %(message)s