name: Test And Document

on:
    push:
        branches: ['main', 'stable']
    workflow_dispatch:
    workflow_call:

permissions:
    id-token: write
    pages: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    test-and-doc:

        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13.1"
            - name: Install requirements
              run: |
                  pip install -r requirements.txt
            - name: Run unit tests
              run: python -m unittest discover -s ./src/tests -p "libtest.py" -v # Change libtest to *test when finished with other tests
            - name: Build docs
              run: |
                git fetch --tags
                cd docs
                mkdir build
                python3 build-docs.py
            - name: Set up pages
              uses: actions/configure-pages@v3
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v5
              with:
                path: './pages'
            - name: Deploy pages
              id: deployment
              uses: actions/deploy-pages@v2
            # - name: "Checkout pages"
            #   uses: actions/checkout@v4
            #   with:
            #     ref: gh-pages
            #     clean: 'false'
            
            # - name: "Update docs"
            #   run: |
            #     rsync -av --delete ./docs/build/html/ ${{github.workspace}}/${{github.ref == 'stable' && 'docs-stable' || 'docs-dev'}}
            
            # - name: "Commit and push"
            #   run: |
            #     git config user.name "github-actions"
            #     git config user.email "github-actions@github.com"
            #     git add .
            #     git commit -m "Update Sphinx docs" || echo "No changes"
            #     git push