name: Test And Document

on:
    push:
        branches: ['main', 'stable']
    workflow_dispatch:
    workflow_call:

permissions:
    id-token: write
    pages: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    test-and-doc:

        if: github.event_name != 'push' || github.event.before != '0000000000000000000000000000000000000000'

        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Check for fast-forward
              run: |
                git fetch origin main
    
                if git merge-base --is-ancestor HEAD origin/main; then
                    echo "No new commits relative to main (likely fast-forward). Skipping CI."
                    exit 0
                fi

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13.1"
            - name: Install requirements
              run: |
                  pip install -r requirements.txt
            - name: Run unit tests
              run: python -m unittest discover -s ./src/tests -p "libtest.py" -v # Change libtest to *test when finished with other tests
            - name: Build docs
              run: |
                git fetch --tags
                cd docs
                mkdir build
                git checkout main -- build-docs.py
                python3 build-docs.py
            - name: Set up pages
              uses: actions/configure-pages@v6
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v5
              with:
                path: './pages'
            - name: Deploy pages
              id: deployment
              uses: actions/deploy-pages@v5