name: Test And Document

on:
    push:
        branches: ['main']
    workflow_dispatch:
    workflow_call:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    test-and-doc:

        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13.1"
            - name: Install requirements
              run: |
                  pip install -r requirements.txt
            - name: Run unit tests
              run: python -m unittest discover -s ./src/tests -p "libtest.py" -v # Change libtest to *test when finished with other tests
            - name: Build docs
              run: |
                docs/make html
            - name: Setup pages
              uses: actions/configure-pages@v5
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: "./docs/build"
            - name: Deploy to Github pages
              id: deployment
              uses: actions/deploy-pages@v4